replicaCount: 1

image:
  repository: 192.168.7.191:5000/crawler
  pullPolicy: Always # IfNotPresent

serviceAccount:
  create: false
  annotations: {}
  name: spider

service:
  type: ClusterIP
  port: 18979

# https://crontab.guru/
cronJob:
  schedule: "* * * * *" # At every minute
  # schedule: "0 * * * *" # At minite 0 (hourly)

secret:
  name: elastic-secret
  type: Opaque

crawler:
  page: 5
  robotObey: "True"
  log:
    level: DEBUG
  concurrentRequest: 2
  delay: 0.5
  encoding: "utf-8"

elastic:
  protocol: http
  host: elasticsearch-master
  port: 9200
  username: elastic
  password: elastic

configMap:
  create: false
  name: "configmap-crawler"
  files: "files/settings.py"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
securityContext: {}
